### Routes 
### using different routes

### Create new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "atolagbe24@gmail.com",
    "password": "proft0011@24"
}

### user signin 
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "atolagbedt@gmail.com",
    "password": "proft001"
}

### get the currently signed in user
GET http://localhost:3000/auth/whoami

### sign out 
POST http://localhost:3000/auth/signout

###find a perticualer user with id
GET http://localhost:3000/auth/1

### find all users with the email
GET http://localhost:3000/auth?email=rancho1sdfff@gmail.com


###delete a perticualer user with id
DELETE http://localhost:3000/auth/994040

### update a user with given address
PATCH http://localhost:3000/auth/4
content-type: application/json

{
    "password": "johndoe123"
}
